#define OPENSSL_API_COMPAT 0x10002000L
#include "cli.hpp"
#include <libsuskmhal/suskmhal.hpp>
#include <libsuskmhal/keymaster-types-c.h>
#include <libsuskmhal/util/km-params.hpp>
#include <libsuskmhal/transport/aosp-hidl-support.hpp>
#include <vector>
#include <cstdlib>
#include <iostream>
#include <semaphore.h>
#include <openssl/rand.h>
#include <openssl/x509.h>

namespace suskeymaster {
namespace cli {
namespace secureimport {
namespace target {

using namespace kmhal::generic;

static void init_attest_key_params(std::vector<KeyParameter>& params);

static int extract_subject_pubkey(std::vector<u8>& out, const std::vector<u8>& cert);

int generate_and_attest_wrapping_key(SusKMHal& hal,
    std::vector<u8>& out_wrapping_blob, std::vector<u8>& out_wrapping_pubkey,
    std::vector<std::vector<u8>> * out_cert_chain,
    std::vector<KeyParameter> const& in_gen_params
)
{
    bool is_rsa = true;
    for (auto const& kp : in_gen_params) {
        if (kp.tag == Tag::ALGORITHM) {
            is_rsa = kp.f.algorithm == Algorithm::RSA;
            break;
        }
    }
    std::vector<KeyParameter> params(in_gen_params);
    if (is_rsa) {
        kmhal::util::init_default_params(params, {
            { Tag::ALGORITHM, Algorithm::RSA },
            { Tag::PURPOSE, { KeyPurpose::WRAP_KEY, KeyPurpose::ENCRYPT, KeyPurpose::DECRYPT } },
            { Tag::KEY_SIZE, 2048 },
            { Tag::RSA_PUBLIC_EXPONENT, 65537 },
            { Tag::DIGEST, { Digest::SHA_2_256 } },
            { Tag::PADDING, { PaddingMode::RSA_OAEP } },
            { Tag::NO_AUTH_REQUIRED, true }
        });

        /* KeyMint requires that asymmetric keys have notBefore and notAfter tags
         * specified during generation */
        if (hal.getVersion() >= kmhal::HAL_KEYMINT_1_0) {
            kmhal::util::init_default_params(params, {
                { Tag::CERTIFICATE_NOT_BEFORE, UINT64_C(0) },
                { Tag::CERTIFICATE_NOT_AFTER, UINT64_C(253402300799000) }
            });

            /* Further, since attestation on KeyMint can only be done during generation,
             * we have to specify the parameters here if the user wanted attestation */
            if (out_cert_chain != nullptr)
                init_attest_key_params(params);
        }
    }

    /** Generate the wrapping RSA-2048 key (along with any attestation, if using KeyMint) **/
    KeyCharacteristics kc;
    std::vector<std::vector<u8>> cert_chain;
    ErrorCode e = hal.generateKey(params, out_wrapping_blob, kc, cert_chain);
    if (e != ErrorCode::OK) {
        std::cerr << "Failed to generate the wrapping key: "
            << static_cast<i32>(e) << " (" << toString(e) << ")" << std::endl;
        return 1;
    }
    std::cout << "Successfully generated wrapping key" << std::endl;

    /** Export the public part **/

    /* KeyMint "exports" the key for us during generation in its returned cert chain,
     * no matter whether full attestation was requested or not */
    if (hal.getVersion() >= kmhal::HAL_KEYMINT_1_0) {
        if (cert_chain.size() == 0) {
            std::cerr << "Invalid cert chain returned by KeyMint generateKey" << std::endl;
            return 1;
        }

        if (extract_subject_pubkey(out_wrapping_pubkey, cert_chain[0])) {
            std::cerr << "Failed to extract the subject public key DER" << std::endl;
            return 1;
        }

        /* If the user requested an attestation, it was generated by `generateKey` */
        if (out_cert_chain != nullptr)
            *out_cert_chain = cert_chain;

        std::cout << "Successfully generated" <<
            (out_cert_chain != nullptr ? " and attested" : "")
             << " the wrapping key" << std::endl;

        /* ...and on KeyMint we're done after just a single `generateKey` call! How awesome! */
        return 0;
    }

    /* On the other hand, Keymaster just has a separate `exportKey` call */
    if (hal_ops::export_key(hal, out_wrapping_blob, params, out_wrapping_pubkey)) {
        std::cerr << "Failed to export the wrapping public key" << std::endl;
        return 1;
    }
    std::cout << "Successfully exported the wrapping public key" << std::endl;


    if (out_cert_chain == nullptr) {
        std::cout << "Successfully generated the wrapping key!" << std::endl;
        return 0;
    }

    /* (optionally, on Keymaster) Generate an attestation for the wrapping key */
    init_attest_key_params(params);
    e = hal.attestKey(out_wrapping_blob, params, *out_cert_chain);
    if (e != ErrorCode::OK) {
        std::cerr << "Failed to attest the wrapping key: "
            << static_cast<i32>(e) << " (" << toString(e) << ")" << std::endl;
        return 1;
    }
    *out_cert_chain = cert_chain;

    std::cout << "Successfully generated and attested the wrapping key" << std::endl;
    return 0;
}

int import_wrapped_key(SusKMHal& hal, std::vector<u8> const& in_wrapped_data,
        std::vector<u8> const& in_masking_key, std::vector<u8> const& in_wrapping_blob,
        std::vector<KeyParameter> const& in_unwrapping_params, std::vector<u8>& out_key_blob
)
{
    std::vector<KeyParameter> params(in_unwrapping_params);
    kmhal::util::init_default_params(params, {
        { Tag::DIGEST, { Digest::SHA_2_256 } },
        { Tag::PADDING, { PaddingMode::RSA_OAEP } }
    });

    KeyCharacteristics kc;
    ErrorCode e = hal.importWrappedKey(in_wrapped_data, in_wrapping_blob,
                in_masking_key, params, 0, 0, out_key_blob, kc);
    if (e != ErrorCode::OK) {
        std::cerr << "importWrappedKey operation failed: "
            << static_cast<i32>(e) << " (" << toString(e) << ")" << std::endl;
        return 1;
    }
    std::cout << "Successfully imported wrapped key" << std::endl;

    return 0;
}

static void init_attest_key_params(std::vector<KeyParameter>& params)
{
    kmhal::util::init_default_params(params, {
        { Tag::ATTESTATION_CHALLENGE, kmhal::util::get_attestation_challenge() },
        { Tag::ATTESTATION_APPLICATION_ID, kmhal::util::get_attestation_application_id() }
    });
}

static int extract_subject_pubkey(std::vector<u8>& out, const std::vector<u8>& cert)
{
    const u8 *p = NULL;
    X509 *x509 = NULL;
    const EVP_PKEY *pubkey = NULL;
    long spki_len = 0;
    u8 *spki_der = NULL;
    out.resize(0);
    int ret = EXIT_FAILURE;

    p = cert.data();
    if ((x509 = d2i_X509(NULL, &p, static_cast<long>(cert.size()))) == NULL) {
        std::cerr << "Failed to deserialize the X.509 cert" << std::endl;
        goto err;
    }

    if ((pubkey = X509_get0_pubkey(x509)) == NULL) {
        std::cerr << "Failed to extract the public key from the X.509 cert" << std::endl;
        goto err;
    }

    spki_len = i2d_PUBKEY(pubkey, NULL);
    if (spki_len <= 0) {
        std::cerr << "Couldn't determine the length of the X.509 public key DER" << std::endl;
        goto err;
    }

    out.resize(static_cast<size_t>(spki_len));
    spki_der = out.data();
    if (i2d_PUBKEY(pubkey, &spki_der) != spki_len) {
        std::cerr << "Failed to serialize the X.509 public key" << std::endl;
        goto err;
    }

    ret = EXIT_SUCCESS;

err:
    spki_der = NULL;
    pubkey = NULL;
    if (x509 != NULL) {
        X509_free(x509);
        x509 = NULL;
    }
    p = NULL;

    if (ret != EXIT_SUCCESS)
        out.resize(0);

    return ret;
}

} /* namespace target */
} /* namespace secureimport */
} /* namespace cli */
} /* namespace suskeymaster */
